# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32e7528dd75f377d9d189d552cc894ce1ff0d8ae665082d1c4680ac534ba55383f9bc25ff9eb6fee84d7739d28989204102094dd0965b6d839c85dd91bd17725

test:
  secret_key_base: 2126e40c9d099c5d1507a5548962f22b685a1952d29f7e8ecfd27554a2428c08e17f65cdc8c67ba6676ebf3f7c29e8eee13974fac55b11e60570677ecb07a252

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
